'use server';
/**
 * @fileOverview AI chatbot flow that supports voice input and output in multiple Indian languages.
 *
 * - aiChatbot - A function that handles the chatbot interaction.
 * - AIChatbotInput - The input type for the aiChatbot function.
 * - AIChatbotOutput - The return type for the aiChatbot function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';
import wav from 'wav';

const AIChatbotInputSchema = z.object({
  language: z.string().describe('The language to use for the chatbot interaction.'),
  query: z.string().describe('The user query for the chatbot.'),
});
export type AIChatbotInput = z.infer<typeof AIChatbotInputSchema>;

// This schema is for the final output of the flow, including audio
const AIChatbotOutputSchema = z.object({
  response: z.string().describe('The chatbot response.'),
  audio: z.string().optional().describe('The audio data of the chatbot response in WAV format as a data URI.'),
});
export type AIChatbotOutput = z.infer<typeof AIChatbotOutputSchema>;

// This schema is specifically for the text-generation part of the prompt
const TextResponseSchema = z.object({
    response: z.string().describe("The chatbot's text response to the user's query."),
});


async function toWav(
  pcmData: Buffer,
  channels = 1,
  rate = 24000,
  sampleWidth = 2
): Promise<string> {
  return new Promise((resolve, reject) => {
    const writer = new wav.Writer({
      channels,
      sampleRate: rate,
      bitDepth: sampleWidth * 8,
    });

    const bufs: any[] = [];
    writer.on('error', reject);
    writer.on('data', function (d) {
      bufs.push(d);
    });
    writer.on('end', function () {
      resolve(Buffer.concat(bufs).toString('base64'));
    });

    writer.write(pcmData);
    writer.end();
  });
}

export async function aiChatbot(input: AIChatbotInput): Promise<AIChatbotOutput> {
  return aiChatbotFlow(input);
}

const prompt = ai.definePrompt({
  name: 'aiChatbotTextPrompt',
  input: {schema: AIChatbotInputSchema},
  output: {schema: TextResponseSchema}, // Use the simpler schema for text generation
  prompt: `You are a helpful AI assistant for Indian farmers. You are an expert on crop care, fertilizer guidance, and seasonal farming tips. Your answer should be helpful and encouraging.

Respond in the user's local language.

Language: {{{language}}}
User's Query: {{{query}}}
`,
});

const aiChatbotFlow = ai.defineFlow(
  {
    name: 'aiChatbotFlow',
    inputSchema: AIChatbotInputSchema,
    outputSchema: AIChatbotOutputSchema,
  },
  async input => {
    // 1. Get the text response from the primary model
    const {output: textOutput} = await prompt(input);
    if (!textOutput?.response) {
      throw new Error('No text response was generated by the AI.');
    }

    // 2. Generate the speech audio from the text response
    const { media } = await ai.generate({
      model: ai.model('gemini-2.5-flash-preview-tts'),
      config: {
        responseModalities: ['AUDIO'],
        speechConfig: {
          voiceConfig: {
            // This is a placeholder. For a real app, you'd map input.language to a specific voice.
            prebuiltVoiceConfig: { voiceName: 'Algenib' },
          },
        },
      },
      prompt: textOutput.response,
    });

    let audioDataUri;
    if (media?.url) {
      const audioBuffer = Buffer.from(
          media.url.substring(media.url.indexOf(',') + 1),
          'base64'
      );
      audioDataUri = 'data:audio/wav;base64,' + (await toWav(audioBuffer));
    }

    // 3. Return both the text and the audio data
    return {
      response: textOutput.response,
      audio: audioDataUri
    };
  }
);
